# Generated by Django 4.0 on 2022-05-26 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_useracticlerelation_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActicleRelation',
            new_name='UserArticleRelation',
        ),
        migrations.AddField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(related_name='rate_articles', through='news.UserArticleRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.customuser'),
        ),
    ]
