# Generated by Django 4.0 on 2022-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_useracticlerelation_userarticlerelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
